-----------------------------------------------------------------
-- 단일행 함수 --
-- 교재 p 71 
-- INITCAP() 함수 
SELECT ename, INITCAP(ename) "INITCAP"
    FROM emp
    WHERE deptno = 10;

-- 교재 p72 / LOWER / UPPER
SELECT ename, LOWER(ename) "LOWER", UPPER(ename) "UPPER"
    FROM emp
    WHERE deptno = 10;

-- 교재 p73 / LENGTH / LENGTHB
SELECT ename, LENGTH(ename) "LENGTH", LENGTHB(ename) "LENGTH"
    FROM emp
    WHERE deptno = 20;

SELECT '서진수' "NAME" , LENGTH('서진수') "LENGTH",
                        LENGTHB('서진수') "LENGTHB"
    FROM dual;

SET verify OFF
SELECT ename, LENGTH(ename)
    FROM emp
    WHERE LENGTH(ename) > LENGTH('&ename');

-- 교재 p74 / CONCAT
SELECT CONCAT(ename, job)
    FROM emp
    WHERE deptno = 10;

-- 교재 p75 / SUBSTR
SELECT  SUBSTR('ABCDE', 3, 2) "3,2" ,
        SUBSTR('ABCDE', -3, 2) "-3,2" ,
        SUBSTR('ABCDE', -3, 4) "-3,4"
FROM DUAL;

-- 교재 P76 / SUBSTRB
SELECT '서진수' "NAME" , SUBSTR('서진수', 1,2) "SUBSTR" ,
                        SUBSTRB('서진수', 1,2) "SUBSTRB"
FROM DUAL;

-- 교재 P77 ~ 79 / INSTR
SELECT NAME, TEL, INSTR(TEL, ')') FROM STUDENT WHERE DEPTNO1 = '201';

SELECT NAME, TEL, INSTR(TEL, '3') FROM STUDENT WHERE DEPTNO1 = '101';

SELECT NAME, TEL, SUBSTR(TEL, 1, INSTR(TEL, ')')-1) AS "AREA CODE" FROM STUDENT WHERE DEPTNO1 = '201';

-- 교재 P80 ~ 82 / LPAD / RPAD
SELECT NAME, ID, LPAD(ID,10,'*') FROM STUDENT WHERE DEPTNO1 = '201';

SELECT LPAD(ENAME, 9, '123456789') AS LPAD FROM EMP WHERE DEPTNO = 10;

SELECT RPAD(ENAME, 10, '-') AS RPAD FROM EMP WHERE DEPTNO = 10;

SELECT RPAD(ENAME, 9, SUBSTR('123456789', LENGTH(ENAME) + 1)) AS RPAD FROM EMP WHERE DEPTNO = 10;

-- 교재 P82 ~ 83 / LTRIM / RTRIM - 제거 ?TRIM(컬럼명,'제거할문자')
SELECT LTRIM(ENAME, 'C') FROM EMP WHERE DEPTNO = 10;

SELECT ENAME, RTRIM(ENAME, 'R') AS RTRIM FROM EMP WHERE DEPTNO = 10;

-- 교재 P83 ~ 85 / REPLACE(컬럼명, '문자1', '문자2')
SELECT ENAME, REPLACE(ENAME, SUBSTR(ENAME,1,2), '**') AS "REPLACE"
    FROM EMP
    WHERE DEPTNO = 10;
    
SELECT ENAME, REPLACE(ENAME, SUBSTR(ENAME,2,2), '--')
    FROM EMP
    WHERE DEPTNO = 20;

SELECT NAME, JUMIN, REPLACE(JUMIN, SUBSTR(JUMIN, 7), '-/-/-/-') AS "REPLACE"
    FROM STUDENT
    WHERE DEPTNO1 = '101';

SELECT NAME, TEL, REPLACE(TEL, SUBSTR(TEL, INSTR(TEL, ')', 1)+1, 3), '***') AS "REPLACE"
    FROM STUDENT
    WHERE DEPTNO1 = '102';




































